"""playoff wins and gameid

Revision ID: bd424fe752b3
Revises: 6f653331b650
Create Date: 2020-08-16 23:45:27.298611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd424fe752b3'
down_revision = '6f653331b650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('gameid', sa.String(), nullable=True))
    op.add_column('team', sa.Column('playoff_wins', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'playoff_wins')
    op.drop_column('game', 'gameid')
    # ### end Alembic commands ###
