"""gameid and playoff wins

Revision ID: dd41501d0e60
Revises: 6f653331b650
Create Date: 2020-08-17 00:01:01.349585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd41501d0e60'
down_revision = '6f653331b650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('gameid', sa.String(length=10), nullable=True))
    op.create_unique_constraint(None, 'game', ['gameid'])
    op.add_column('team', sa.Column('playoff_wins', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'playoff_wins')
    op.drop_constraint(None, 'game', type_='unique')
    op.drop_column('game', 'gameid')
    # ### end Alembic commands ###
